/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import BLL.*;
import static BLL.BLL_PhieuThue.UpDownDate;
import DAL.*;
import DTO.*;
import DAL.DAL_Quyen;
import static GUI.pnl_Quyen.tblQuyen;

import static GUI.pnl_DocGia.tblDocGia;
import static GUI.pnl_DocGia.cbbLoaiDG;
import static GUI.pnl_LoaiDocGia.tblLoaiDocGia;
import static GUI.pnl_TacGia.tblTacGia;
import static GUI.pnl_khuyenmai.tbl_km;
import static GUI.pnl_PhieuPhat.tblSach;
import static GUI.pnl_PhieuPhat.cbbNhanVien_PP;
import static GUI.pnl_PhieuPhat.cbbDocGia_PP;
import static GUI.pnl_PhieuPhat.txtNgayPhat_PP;
import static GUI.pnl_PhieuPhat.tblSachPhat;

import static GUI.pnl_nhapkho.tblPhieuNhap;
import static GUI.pnl_nhapkho.tbl_spnhap;
import static GUI.pnl_nhapkho.txt_TimKiem_PN;
import static GUI.pnl_nhapkho.cbb_NCC_PN;
import static GUI.pnl_nhapkho.cbb_NhanVien_PN;
import static GUI.pnl_nhapkho.txtSoPhieuNhap;
import static GUI.pnl_nhapkho.txtNgayTao_PN;
import static GUI.pnl_nhapkho.tblPhieuNhap;

import static GUI.pnl_nhacungcap.tblNCC;
import static GUI.pnl_nhapkho.tbl_spnhap;
import static GUI.pnl_giahan_trasach.tblPhieuThue_GHTS;
import static GUI.pnl_giahan_trasach.txtTimKiem_GH;
import static GUI.pnl_TheLoai.*;
import static GUI.pnl_danhmucsach.tbl_sach;
import static GUI.pnl_nhanvien.tblnhanvien;
import static GUI.pnl_nhanvien.cbbQuyen;
import javax.swing.table.DefaultTableModel;
import static GUI.pnl_PhieuPhat.txtSoPhieuPhat;

import static GUI.pnl_PhieuThue.tbnThongTinSach;
import static GUI.pnl_PhieuThue.cbbNhanVien;
import static GUI.pnl_PhieuThue.txtSoPhieuThue;
import static GUI.pnl_PhieuThue.txtMaPhieuThue;
import static GUI.pnl_PhieuThue.cbbDocGia_PT;
import static GUI.pnl_PhieuPhat.txtTimKiem_PP;
import static GUI.pnl_PhieuThue.txtTimKiem_PTP;
import static GUI.pnl_PhieuThue.tblSachMuon_PT;
import java.awt.Toolkit;
import java.util.Calendar;


//import DAL.DAL_DocGia;
//import static GUI.pnl_DocGia.*;
//import DAL.DAL_TacGia;
//import static GUI.pnl_TacGia.*;
//import DAL.DAL_NhaCungCap;
//import static GUI.pnl_Quyen.tblQuyen;
//import DAL.DAL_ChiTietPhieuPhat;
//import static GUI.pnl_Quyen.tblQuyen;
/**
 *
 * @author Huy Nhan
 */
public class frm_main extends javax.swing.JFrame {

    /**
     * Creates new form frm_main
     */
    public frm_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbn_menu = new javax.swing.JTabbedPane();
        pnl_hethong = new javax.swing.JPanel();
        pnl_ht = new javax.swing.JPanel();
        btn_doimatkhau = new javax.swing.JButton();
        btn_dangxuat = new javax.swing.JButton();
        btn_gioithieu = new javax.swing.JButton();
        btn_gioithieu1 = new javax.swing.JButton();
        lbl_ngay = new javax.swing.JLabel();
        lbl_gio = new javax.swing.JLabel();
        pnl_muonthongke = new javax.swing.JPanel();
        pnl_muontragiahan = new javax.swing.JPanel();
        lbl_muontratieude = new javax.swing.JLabel();
        btn_PhieuThue = new javax.swing.JButton();
        btn_Giahan_Trasach = new javax.swing.JButton();
        btn_PhieuPhat = new javax.swing.JButton();
        pnl_baocao = new javax.swing.JPanel();
        lbl_baocaotieude = new javax.swing.JLabel();
        btn_doanhthu = new javax.swing.JButton();
        pnl_kho1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnThanhLy1 = new javax.swing.JButton();
        pnl_CapnhapQuanly = new javax.swing.JPanel();
        pnl_docgia = new javax.swing.JPanel();
        lbl_docgiatieude = new javax.swing.JLabel();
        btn_DocGia = new javax.swing.JButton();
        btn_LoaiDocGia = new javax.swing.JButton();
        pnl_nhanvien = new javax.swing.JPanel();
        lbl_nhanvientieude = new javax.swing.JLabel();
        btn_NhanVien = new javax.swing.JButton();
        btn_phanquyen = new javax.swing.JButton();
        pnl_sach = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnSach = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        pnl_kho = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnThanhLy = new javax.swing.JButton();
        btnPhieuNhap = new javax.swing.JButton();
        pnl_tacgiatheloai = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnTacGia = new javax.swing.JButton();
        btnTheLoai = new javax.swing.JButton();
        btnNCC = new javax.swing.JButton();
        pnl_thongtin = new javax.swing.JPanel();
        lbl_maytru = new javax.swing.JLabel();
        lbl_nguoisudung = new javax.swing.JLabel();
        lbl_quyenhan = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        lbl_ttmaytru = new javax.swing.JLabel();
        lbl_ttnguoisudung = new javax.swing.JLabel();
        lbl_ttquyenhan = new javax.swing.JLabel();
        tbn_main = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần Mềm Quản Lý Thư Viên");
        setBackground(new java.awt.Color(51, 153, 255));
        setMinimumSize(new java.awt.Dimension(1365, 710));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbn_menu.setBackground(new java.awt.Color(0, 153, 255));
        tbn_menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbn_menu.setForeground(new java.awt.Color(255, 255, 255));
        tbn_menu.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tbn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbn_menu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        pnl_hethong.setBackground(new java.awt.Color(0, 153, 204));

        pnl_ht.setBackground(new java.awt.Color(0, 153, 204));
        pnl_ht.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_doimatkhau.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_doimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ changePassword48x48.png"))); // NOI18N
        btn_doimatkhau.setText("Đổi mật khẩu");
        btn_doimatkhau.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_doimatkhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_doimatkhau.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_doimatkhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_doimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doimatkhauActionPerformed(evt);
            }
        });

        btn_dangxuat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogOut48x48.png"))); // NOI18N
        btn_dangxuat.setText("Đăng xuất");
        btn_dangxuat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_dangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dangxuat.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_dangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btn_gioithieu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_gioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help48x48.png"))); // NOI18N
        btn_gioithieu.setText("Giới thiệu");
        btn_gioithieu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_gioithieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_gioithieu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_gioithieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_gioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gioithieuActionPerformed(evt);
            }
        });

        btn_gioithieu1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_gioithieu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/KM.png"))); // NOI18N
        btn_gioithieu1.setText("Khuyến mãi");
        btn_gioithieu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_gioithieu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_gioithieu1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_gioithieu1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_gioithieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gioithieu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_htLayout = new javax.swing.GroupLayout(pnl_ht);
        pnl_ht.setLayout(pnl_htLayout);
        pnl_htLayout.setHorizontalGroup(
            pnl_htLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_htLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_doimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_gioithieu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_gioithieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_htLayout.setVerticalGroup(
            pnl_htLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_htLayout.createSequentialGroup()
                .addGroup(pnl_htLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_gioithieu1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_htLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_doimatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addComponent(btn_gioithieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );

        lbl_ngay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ngay.setForeground(new java.awt.Color(255, 0, 0));

        lbl_gio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_gio.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnl_hethongLayout = new javax.swing.GroupLayout(pnl_hethong);
        pnl_hethong.setLayout(pnl_hethongLayout);
        pnl_hethongLayout.setHorizontalGroup(
            pnl_hethongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_hethongLayout.createSequentialGroup()
                .addComponent(pnl_ht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 632, Short.MAX_VALUE)
                .addGroup(pnl_hethongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_hethongLayout.createSequentialGroup()
                        .addComponent(lbl_gio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addComponent(lbl_ngay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnl_hethongLayout.setVerticalGroup(
            pnl_hethongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_ht, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_hethongLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_gio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbn_menu.addTab("Hệ Thống", pnl_hethong);

        pnl_muonthongke.setBackground(new java.awt.Color(0, 153, 204));

        pnl_muontragiahan.setBackground(new java.awt.Color(0, 153, 204));
        pnl_muontragiahan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_muontratieude.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_muontratieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_muontratieude.setText("Mượn - trả - gia hạn sách-phạt");
        lbl_muontratieude.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_PhieuThue.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_PhieuThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/theory48x48.png"))); // NOI18N
        btn_PhieuThue.setText("Cho Mượn");
        btn_PhieuThue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_PhieuThue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_PhieuThue.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_PhieuThue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_PhieuThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PhieuThueActionPerformed(evt);
            }
        });

        btn_Giahan_Trasach.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_Giahan_Trasach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Things-Book48x48.png"))); // NOI18N
        btn_Giahan_Trasach.setText("Trả Sách - Gia Hạn");
        btn_Giahan_Trasach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Giahan_Trasach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Giahan_Trasach.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_Giahan_Trasach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Giahan_Trasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Giahan_TrasachActionPerformed(evt);
            }
        });

        btn_PhieuPhat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_PhieuPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/theory48x48.png"))); // NOI18N
        btn_PhieuPhat.setText("Phạt");
        btn_PhieuPhat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_PhieuPhat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_PhieuPhat.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_PhieuPhat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_PhieuPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PhieuPhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_muontragiahanLayout = new javax.swing.GroupLayout(pnl_muontragiahan);
        pnl_muontragiahan.setLayout(pnl_muontragiahanLayout);
        pnl_muontragiahanLayout.setHorizontalGroup(
            pnl_muontragiahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_muontragiahanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_PhieuThue, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Giahan_Trasach, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_PhieuPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbl_muontratieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_muontragiahanLayout.setVerticalGroup(
            pnl_muontragiahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_muontragiahanLayout.createSequentialGroup()
                .addGroup(pnl_muontragiahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Giahan_Trasach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_PhieuThue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_PhieuPhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_muontratieude, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_baocao.setBackground(new java.awt.Color(0, 153, 204));
        pnl_baocao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_baocaotieude.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_baocaotieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_baocaotieude.setText("Báo Cáo - Thống Kê");
        lbl_baocaotieude.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_doanhthu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_doanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chart-icon32x32.png"))); // NOI18N
        btn_doanhthu.setText("Doanh thu");
        btn_doanhthu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_doanhthu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_doanhthu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_doanhthu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_doanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doanhthuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_baocaoLayout = new javax.swing.GroupLayout(pnl_baocao);
        pnl_baocao.setLayout(pnl_baocaoLayout);
        pnl_baocaoLayout.setHorizontalGroup(
            pnl_baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_baocaotieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_baocaoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btn_doanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnl_baocaoLayout.setVerticalGroup(
            pnl_baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_baocaoLayout.createSequentialGroup()
                .addComponent(btn_doanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_baocaotieude, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_kho1.setBackground(new java.awt.Color(0, 153, 204));
        pnl_kho1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Bán sách");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnThanhLy1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnThanhLy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/payment-icon48x48.png"))); // NOI18N
        btnThanhLy1.setText("Bán");
        btnThanhLy1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnThanhLy1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThanhLy1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnThanhLy1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThanhLy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhLy1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_kho1Layout = new javax.swing.GroupLayout(pnl_kho1);
        pnl_kho1.setLayout(pnl_kho1Layout);
        pnl_kho1Layout.setHorizontalGroup(
            pnl_kho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kho1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThanhLy1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_kho1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        pnl_kho1Layout.setVerticalGroup(
            pnl_kho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_kho1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnThanhLy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnl_muonthongkeLayout = new javax.swing.GroupLayout(pnl_muonthongke);
        pnl_muonthongke.setLayout(pnl_muonthongkeLayout);
        pnl_muonthongkeLayout.setHorizontalGroup(
            pnl_muonthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_muonthongkeLayout.createSequentialGroup()
                .addComponent(pnl_muontragiahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_kho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_baocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 708, Short.MAX_VALUE))
        );
        pnl_muonthongkeLayout.setVerticalGroup(
            pnl_muonthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_muontragiahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_baocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_kho1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbn_menu.addTab("Mượn Sách - Trả Sách - Thống Kê", pnl_muonthongke);

        pnl_CapnhapQuanly.setBackground(new java.awt.Color(0, 153, 204));

        pnl_docgia.setBackground(new java.awt.Color(0, 153, 204));
        pnl_docgia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_docgiatieude.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_docgiatieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_docgiatieude.setText("Độc giả");
        lbl_docgiatieude.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_DocGia.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_DocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-group48x48.png"))); // NOI18N
        btn_DocGia.setText("Danh sách");
        btn_DocGia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_DocGia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_DocGia.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_DocGia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_DocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DocGiaActionPerformed(evt);
            }
        });

        btn_LoaiDocGia.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_LoaiDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excel-icon24x24.png"))); // NOI18N
        btn_LoaiDocGia.setText("Loại độc giả");
        btn_LoaiDocGia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_LoaiDocGia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_LoaiDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoaiDocGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_docgiaLayout = new javax.swing.GroupLayout(pnl_docgia);
        pnl_docgia.setLayout(pnl_docgiaLayout);
        pnl_docgiaLayout.setHorizontalGroup(
            pnl_docgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_docgiaLayout.createSequentialGroup()
                .addComponent(lbl_docgiatieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnl_docgiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_DocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_LoaiDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_docgiaLayout.setVerticalGroup(
            pnl_docgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_docgiaLayout.createSequentialGroup()
                .addGroup(pnl_docgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_DocGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_docgiaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_LoaiDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_docgiatieude, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_nhanvien.setBackground(new java.awt.Color(0, 153, 204));
        pnl_nhanvien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_nhanvientieude.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_nhanvientieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nhanvientieude.setText("Nhân viên thư viện");
        lbl_nhanvientieude.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_NhanVien.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-group-icon48x48.png"))); // NOI18N
        btn_NhanVien.setText("Danh sách");
        btn_NhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_NhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_NhanVien.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_NhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhanVienActionPerformed(evt);
            }
        });

        btn_phanquyen.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_phanquyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-rating-icon.png"))); // NOI18N
        btn_phanquyen.setText("quyền");
        btn_phanquyen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_phanquyen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_phanquyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phanquyenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_nhanvienLayout = new javax.swing.GroupLayout(pnl_nhanvien);
        pnl_nhanvien.setLayout(pnl_nhanvienLayout);
        pnl_nhanvienLayout.setHorizontalGroup(
            pnl_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_nhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_phanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbl_nhanvientieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_nhanvienLayout.setVerticalGroup(
            pnl_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_nhanvienLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnl_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_nhanvienLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_phanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nhanvientieude, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_sach.setBackground(new java.awt.Color(0, 153, 204));
        pnl_sach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sách");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnSach.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/research48x48.png"))); // NOI18N
        btnSach.setText("Danh mục");
        btnSach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSach.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSachActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button-Add-icon24x24.png"))); // NOI18N
        jButton20.setText("Thêm");
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_sachLayout = new javax.swing.GroupLayout(pnl_sach);
        pnl_sach.setLayout(pnl_sachLayout);
        pnl_sachLayout.setHorizontalGroup(
            pnl_sachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSach, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_sachLayout.setVerticalGroup(
            pnl_sachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_sachLayout.createSequentialGroup()
                .addGroup(pnl_sachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_sachLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_kho.setBackground(new java.awt.Color(0, 153, 204));
        pnl_kho.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Kho");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnThanhLy.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnThanhLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/payment-icon48x48.png"))); // NOI18N
        btnThanhLy.setText("Thanh lý");
        btnThanhLy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnThanhLy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThanhLy.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnThanhLy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThanhLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhLyActionPerformed(evt);
            }
        });

        btnPhieuNhap.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/import-icon48x48.png"))); // NOI18N
        btnPhieuNhap.setText("Nhập kho");
        btnPhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPhieuNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPhieuNhap.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPhieuNhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_khoLayout = new javax.swing.GroupLayout(pnl_kho);
        pnl_kho.setLayout(pnl_khoLayout);
        pnl_khoLayout.setHorizontalGroup(
            pnl_khoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_khoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThanhLy, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_khoLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        pnl_khoLayout.setVerticalGroup(
            pnl_khoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_khoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnl_khoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThanhLy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPhieuNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_tacgiatheloai.setBackground(new java.awt.Color(0, 153, 204));
        pnl_tacgiatheloai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tác giả - Thể loại - Nhà cung cấp");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnTacGia.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/authors-icon48x48.png"))); // NOI18N
        btnTacGia.setText("Tác giả");
        btnTacGia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTacGia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTacGia.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnTacGia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacGiaActionPerformed(evt);
            }
        });

        btnTheLoai.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Categories-gnome-applications-icon48x48.png"))); // NOI18N
        btnTheLoai.setText("Thể loại");
        btnTheLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTheLoai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTheLoai.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnTheLoai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheLoaiActionPerformed(evt);
            }
        });

        btnNCC.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/authors-icon48x48.png"))); // NOI18N
        btnNCC.setText("Nhà CC");
        btnNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNCC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNCC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNCC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_tacgiatheloaiLayout = new javax.swing.GroupLayout(pnl_tacgiatheloai);
        pnl_tacgiatheloai.setLayout(pnl_tacgiatheloaiLayout);
        pnl_tacgiatheloaiLayout.setHorizontalGroup(
            pnl_tacgiatheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tacgiatheloaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_tacgiatheloaiLayout.setVerticalGroup(
            pnl_tacgiatheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tacgiatheloaiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnl_tacgiatheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTheLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_tacgiatheloaiLayout.createSequentialGroup()
                        .addGroup(pnl_tacgiatheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTacGia)
                            .addComponent(btnNCC))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnl_CapnhapQuanlyLayout = new javax.swing.GroupLayout(pnl_CapnhapQuanly);
        pnl_CapnhapQuanly.setLayout(pnl_CapnhapQuanlyLayout);
        pnl_CapnhapQuanlyLayout.setHorizontalGroup(
            pnl_CapnhapQuanlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CapnhapQuanlyLayout.createSequentialGroup()
                .addComponent(pnl_docgia, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_sach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_kho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_tacgiatheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_CapnhapQuanlyLayout.setVerticalGroup(
            pnl_CapnhapQuanlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_docgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_nhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_sach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_kho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_tacgiatheloai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbn_menu.addTab("Cập nhập - Quản lý", pnl_CapnhapQuanly);

        pnl_thongtin.setBackground(new java.awt.Color(102, 204, 255));
        pnl_thongtin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_maytru.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_maytru.setText("Máy chủ :");

        lbl_nguoisudung.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_nguoisudung.setText("Người sử dụng :");

        lbl_quyenhan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_quyenhan.setText("Quyền hạn :");

        lbl_ttmaytru.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lbl_ttnguoisudung.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lbl_ttquyenhan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout pnl_thongtinLayout = new javax.swing.GroupLayout(pnl_thongtin);
        pnl_thongtin.setLayout(pnl_thongtinLayout);
        pnl_thongtinLayout.setHorizontalGroup(
            pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_thongtinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_maytru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ttmaytru, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbl_nguoisudung)
                .addGap(18, 18, 18)
                .addComponent(lbl_ttnguoisudung, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_quyenhan)
                .addGap(18, 18, 18)
                .addComponent(lbl_ttquyenhan, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_thongtinLayout.setVerticalGroup(
            pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_thongtinLayout.createSequentialGroup()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_quyenhan)
                    .addComponent(lbl_ttquyenhan, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(lbl_ttmaytru, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_maytru)
                .addComponent(lbl_nguoisudung)
                .addComponent(lbl_ttnguoisudung, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbn_main.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbn_menu)
            .addComponent(tbn_main)
            .addComponent(pnl_thongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(tbn_main)
                .addGap(1, 1, 1)
                .addComponent(pnl_thongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        setSize(new java.awt.Dimension(1386, 743));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static int CNSach;
    private void btn_doanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doanhthuActionPerformed
        pnl_doanhthu pnl = new pnl_doanhthu();
        BLL_main.themtab("Doanh thu", tbn_main, pnl);
    }//GEN-LAST:event_btn_doanhthuActionPerformed

    private void btn_doimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doimatkhauActionPerformed
        frm_doimatkhau pnl = new frm_doimatkhau();
        pnl.show();
    }//GEN-LAST:event_btn_doimatkhauActionPerformed

    private void btn_gioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gioithieuActionPerformed
        pnl_gioithieu pnl = new pnl_gioithieu();
        BLL_main.themtab("Giới thiệu", tbn_main, pnl);
        
    }//GEN-LAST:event_btn_gioithieuActionPerformed

    private void btnSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSachActionPerformed
        pnl_danhmucsach pnl = new pnl_danhmucsach();
        BLL_main.themtab("Danh mục sách", tbn_main, pnl);

        BLL_sach.DLTable(tbl_sach, DAL.DAL_Sach.GetAll());
    }//GEN-LAST:event_btnSachActionPerformed

  
    private void btn_phanquyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phanquyenActionPerformed
        pnl_Quyen pnl = new pnl_Quyen();
        BLL_main.themtab("Quyền", tbn_main, pnl);
        BLL.BLL_Quyen.DLTable(tblQuyen,DAL_Quyen.GetAll());
    }//GEN-LAST:event_btn_phanquyenActionPerformed

    private void btnTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheLoaiActionPerformed
        pnl_TheLoai pnl = new pnl_TheLoai();
        BLL_main.themtab("Thể Loại", tbn_main, pnl);
        BLL.BLL_TheLoai.DLTable(tblTheLoai, DAL_TheLoai.GetAll());
    }//GEN-LAST:event_btnTheLoaiActionPerformed


    
    private void btn_PhieuThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PhieuThueActionPerformed
        pnl_PhieuThue pnl = new pnl_PhieuThue();
        BLL_main.themtab("Phiếu mượn", tbn_main, pnl);
        
        String seach = txtTimKiem_PTP.getText();
        DefaultTableModel table = (DefaultTableModel)tbnThongTinSach.getModel();
        BLL.BLL_PhieuThue.ThongTinSach(table, seach);
        
        //load Dữ liệu vào cbb Độc giả
        BLL_PhieuThue.FillDataToCBB_DocGia(cbbDocGia_PT);
        BLL_PhieuThue.FillDataToCBB_NhanVien(cbbNhanVien);
        
        //Tạo mã hóa đơn tự động:
        txtSoPhieuThue.setText(BLL_PhieuThue.TaoSoHoaDon());
        // Ngày lập hóa đơn:
        pnl_PhieuThue.txtNgayMuon.setText(BLL_PhieuThue.TaoNgayLapHoaDon());
       
    }//GEN-LAST:event_btn_PhieuThueActionPerformed

    private void btn_DocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DocGiaActionPerformed
        pnl_DocGia pnl = new pnl_DocGia();
        BLL_main.themtab("Độc giả", tbn_main, pnl);        
        BLL.BLL_DocGia.DuLieuDatabase_Table(tblDocGia,DAL.DAL_DocGia.GetAll());
        BLL_DocGia.FillDataToCBB_DocGia(cbbLoaiDG);
    }//GEN-LAST:event_btn_DocGiaActionPerformed

    private void btnTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacGiaActionPerformed
        pnl_TacGia pnl = new pnl_TacGia();
        BLL_main.themtab("Tác Giả", tbn_main, pnl);
     BLL.BLL_TacGia.DuLieuDatabase_Table(tblTacGia,DAL.DAL_TacGia.GetAll());
    }//GEN-LAST:event_btnTacGiaActionPerformed

    private void btn_PhieuPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PhieuPhatActionPerformed
        pnl_PhieuPhat pnl = new pnl_PhieuPhat();
        BLL_main.themtab("Phiếu Phạt", tbn_main, pnl);
        String seach = txtTimKiem_PP.getText();
        DefaultTableModel table = (DefaultTableModel) tblSach.getModel();
        BLL.BLL_PhieuPhat.ThongTinSach(table, seach);
        
        // load dữ liệu vào cbb nhân viên và độc giả
        BLL_PhieuPhat.FillDataToCBB_DocGia(cbbDocGia_PP);
        BLL_PhieuPhat.FillDataToCBB_NhanVien(cbbNhanVien_PP);
        
        //Tạo mã hóa đơn tự động:
           txtSoPhieuPhat.setText(BLL_PhieuPhat.TaoSoHoaDon());
        // Ngày lập hóa đơn:
          txtNgayPhat_PP.setText(BLL_PhieuPhat.TaoNgayLapHoaDon());
        
    }//GEN-LAST:event_btn_PhieuPhatActionPerformed

    private void btn_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhanVienActionPerformed
        pnl_nhanvien pnl = new pnl_nhanvien();
        BLL_main.themtab("Nhân Viên", tbn_main, pnl);
        BLL.BLL_NhanVien.DuLieuDatabase_Table(tblnhanvien,DAL.DAL_NhanVien.GetAll());
        BLL_NhanVien.FillDataToCBB_NhanVien(cbbQuyen);
    }//GEN-LAST:event_btn_NhanVienActionPerformed

    private void btn_Giahan_TrasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Giahan_TrasachActionPerformed
        pnl_giahan_trasach pnl = new pnl_giahan_trasach();
        BLL_main.themtab("Gia hạn-Trả sách", tbn_main, pnl);
        String seach = txtTimKiem_GH.getText();
        DefaultTableModel table = (DefaultTableModel) tblPhieuThue_GHTS.getModel();
        BLL.BLL_PhieuThue.ThongTinPhieuThue(table, seach); 
        
    }//GEN-LAST:event_btn_Giahan_TrasachActionPerformed

    private void btnNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNCCActionPerformed
        pnl_nhacungcap pnl = new pnl_nhacungcap();
        BLL_main.themtab("Nhà cung cấp", tbn_main, pnl);
        BLL.BLL_NhaCungCap.DuLieuDatabase_Table(tblNCC,DAL.DAL_NhaCungCap.GetAll()); 
    }//GEN-LAST:event_btnNCCActionPerformed

    private void btn_gioithieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gioithieu1ActionPerformed
        pnl_khuyenmai pnl = new pnl_khuyenmai();
        BLL_main.themtab("Khuyến mãi", tbn_main, pnl);
    }//GEN-LAST:event_btn_gioithieu1ActionPerformed
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        BLL_clock.clock();
    }//GEN-LAST:event_formWindowOpened

    private void btnThanhLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhLyActionPerformed
        pnl_PhieuThanhLy pnl = new pnl_PhieuThanhLy();
        BLL_main.themtab("Thanh lý", tbn_main, pnl);
        BLL_phieuthanhly.ThongTinSach((DefaultTableModel)pnl_PhieuThanhLy.tblSach.getModel(), DAL_Sach.GetAll());
        BLL_Combobox.LayDuLieuCombobox(DAL_NhanVien.GetAll(), pnl_PhieuThanhLy.cbbNhanVien, "TenNhanVien", "MaNhanVien");
        pnl_PhieuThanhLy.txtSoPhieu.setText(ChuyenDoi_ThongBao.TaoSoHoaDon());
        pnl_PhieuThanhLy.txt_ngaythanhly.setText(ChuyenDoi_ThongBao.TaoNgayLapHoaDon());
    }//GEN-LAST:event_btnThanhLyActionPerformed

    private void btnPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuNhapActionPerformed
       pnl_nhapkho pnl = new pnl_nhapkho();
        BLL_main.themtab("Nhập kho", tbn_main, pnl);
        String seach = txt_TimKiem_PN.getText();
        DefaultTableModel table = (DefaultTableModel) tbl_spnhap.getModel();
        BLL.BLL_PhieuNhap.ThongTinSach(table, seach);
        
        // load dữ liệu vào cbb nhân viên và độc giả
        BLL_PhieuNhap.FillDataToCBB_NCC(cbb_NCC_PN);
        BLL_PhieuNhap.FillDataToCBB_NhanVien(cbb_NhanVien_PN);
        
        //Tạo mã hóa đơn tự động:
           txtSoPhieuNhap.setText(BLL_PhieuNhap.TaoSoHoaDon());
        // Ngày lập hóa đơn:
          txtNgayTao_PN.setText(BLL_PhieuNhap.TaoNgayLapHoaDon());
    }//GEN-LAST:event_btnPhieuNhapActionPerformed


    private void btn_nhapexdocgia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhapexdocgia2ActionPerformed
        pnl_LoaiDocGia pnl = new pnl_LoaiDocGia();
        BLL_main.themtab("Loại độc giả", tbn_main, pnl);
    }//GEN-LAST:event_btn_nhapexdocgia2ActionPerformed

    private void btn_LoaiDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoaiDocGiaActionPerformed
        pnl_LoaiDocGia pnl = new pnl_LoaiDocGia();
        BLL_main.themtab("Loại độc giả", tbn_main, pnl);
          BLL.BLL_LoaiDocGia.DLTable(tblLoaiDocGia,DAL_LoaiDocGia.GetAll());
    }//GEN-LAST:event_btn_LoaiDocGiaActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        
        DuAn1.frm_TTsach.setVisible(true);
        CNSach = 2; 
    }//GEN-LAST:event_jButton20ActionPerformed

    private void btnThanhLy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhLy1ActionPerformed
        pnl_PhieuThanhLy pnl = new pnl_PhieuThanhLy();
        BLL_main.themtab("Thanh lý", tbn_main, pnl);
        BLL_phieuthanhly.ThongTinSach((DefaultTableModel)pnl_PhieuThanhLy.tblSach.getModel(), DAL_Sach.GetAll());
        BLL_Combobox.LayDuLieuCombobox(DAL_NhanVien.GetAll(), pnl_PhieuThanhLy.cbbNhanVien, "TenNhanVien", "MaNhanVien");
        pnl_PhieuThanhLy.txtSoPhieu.setText(ChuyenDoi_ThongBao.TaoSoHoaDon());
        pnl_PhieuThanhLy.txt_ngaythanhly.setText(ChuyenDoi_ThongBao.TaoNgayLapHoaDon());
    }//GEN-LAST:event_btnThanhLy1ActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNCC;
    private javax.swing.JButton btnPhieuNhap;
    private javax.swing.JButton btnSach;
    private javax.swing.JButton btnTacGia;
    private javax.swing.JButton btnThanhLy;
    private javax.swing.JButton btnThanhLy1;
    private javax.swing.JButton btnTheLoai;
    private javax.swing.JButton btn_DocGia;
    private javax.swing.JButton btn_Giahan_Trasach;
    private javax.swing.JButton btn_LoaiDocGia;
    private javax.swing.JButton btn_NhanVien;
    private javax.swing.JButton btn_PhieuPhat;
    private javax.swing.JButton btn_PhieuThue;
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JButton btn_doanhthu;
    private javax.swing.JButton btn_doimatkhau;
    private javax.swing.JButton btn_gioithieu;
    private javax.swing.JButton btn_gioithieu1;
    private javax.swing.JButton btn_phanquyen;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_baocaotieude;
    private javax.swing.JLabel lbl_docgiatieude;
    public static javax.swing.JLabel lbl_gio;
    private javax.swing.JLabel lbl_maytru;
    private javax.swing.JLabel lbl_muontratieude;
    public static javax.swing.JLabel lbl_ngay;
    private javax.swing.JLabel lbl_nguoisudung;
    private javax.swing.JLabel lbl_nhanvientieude;
    private javax.swing.JLabel lbl_quyenhan;
    public static javax.swing.JLabel lbl_ttmaytru;
    public static javax.swing.JLabel lbl_ttnguoisudung;
    public static javax.swing.JLabel lbl_ttquyenhan;
    private javax.swing.JPanel pnl_CapnhapQuanly;
    private javax.swing.JPanel pnl_baocao;
    private javax.swing.JPanel pnl_docgia;
    private javax.swing.JPanel pnl_hethong;
    private javax.swing.JPanel pnl_ht;
    private javax.swing.JPanel pnl_kho;
    private javax.swing.JPanel pnl_kho1;
    private javax.swing.JPanel pnl_muonthongke;
    private javax.swing.JPanel pnl_muontragiahan;
    private javax.swing.JPanel pnl_nhanvien;
    private javax.swing.JPanel pnl_sach;
    private javax.swing.JPanel pnl_tacgiatheloai;
    private javax.swing.JPanel pnl_thongtin;
    public static javax.swing.JTabbedPane tbn_main;
    private javax.swing.JTabbedPane tbn_menu;
    // End of variables declaration//GEN-END:variables
}
