/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import BLL.*;
import DAL.DAL_Quyen;
import static GUI.pnl_Quyen.tblQuyen;
//import DAL.DAL_DocGia;
//import static GUI.pnl_DocGia.*;
//import DAL.DAL_TacGia;
//import static GUI.pnl_TacGia.*;
//import DAL.DAL_NhaCungCap;
//import static GUI.pnl_Quyen.tblQuyen;
//import DAL.DAL_ChiTietPhieuPhat;
//import static GUI.pnl_Quyen.tblQuyen;
/**
 *
 * @author Huy Nhan
 */
public class frm_main extends javax.swing.JFrame {

    /**
     * Creates new form frm_main
     */
    public frm_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbn_menu = new javax.swing.JTabbedPane();
        pnl_hethong = new javax.swing.JPanel();
        pnl_ht = new javax.swing.JPanel();
        btn_nguoidung = new javax.swing.JButton();
        btn_doimatkhau = new javax.swing.JButton();
        btn_dangxuat = new javax.swing.JButton();
        btn_gioithieu = new javax.swing.JButton();
        btn_gioithieu1 = new javax.swing.JButton();
        pnl_muonthongke = new javax.swing.JPanel();
        pnl_muontragiahan = new javax.swing.JPanel();
        lbl_muontratieude = new javax.swing.JLabel();
        btn_chomuon = new javax.swing.JButton();
        btn_trasachgiahan = new javax.swing.JButton();
        btn_chomuon1 = new javax.swing.JButton();
        pnl_baocao = new javax.swing.JPanel();
        lbl_baocaotieude = new javax.swing.JLabel();
        btn_sachcon = new javax.swing.JButton();
        btn_doanhthu = new javax.swing.JButton();
        pnl_CapnhapQuanly = new javax.swing.JPanel();
        pnl_docgia = new javax.swing.JPanel();
        lbl_docgiatieude = new javax.swing.JLabel();
        btn_danhsachdocgia = new javax.swing.JButton();
        btn_nhapexdocgia = new javax.swing.JButton();
        pnl_nhanvien = new javax.swing.JPanel();
        lbl_nhanvientieude = new javax.swing.JLabel();
        btn_danhsachnhanvien = new javax.swing.JButton();
        btn_phanquyen = new javax.swing.JButton();
        btn_nhapexdocgia1 = new javax.swing.JButton();
        pnl_sach = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        pnl_kho = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        pnl_tacgiatheloai = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        pnl_Congcu = new javax.swing.JPanel();
        pnl_thongtin = new javax.swing.JPanel();
        lbl_maytru = new javax.swing.JLabel();
        lbl_nguoisudung = new javax.swing.JLabel();
        lbl_quyenhan = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        tbn_main = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần Mềm Quản Lý Thư Viên");
        setBackground(new java.awt.Color(51, 153, 255));
        setMinimumSize(new java.awt.Dimension(1365, 710));
        setPreferredSize(new java.awt.Dimension(1365, 710));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbn_menu.setBackground(new java.awt.Color(0, 153, 255));
        tbn_menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbn_menu.setForeground(new java.awt.Color(255, 255, 255));
        tbn_menu.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tbn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbn_menu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        pnl_hethong.setBackground(new java.awt.Color(0, 153, 204));

        pnl_ht.setBackground(new java.awt.Color(0, 153, 204));
        pnl_ht.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_nguoidung.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_nguoidung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user48x48.png"))); // NOI18N
        btn_nguoidung.setText("Người dùng");
        btn_nguoidung.setAlignmentX(1.0F);
        btn_nguoidung.setAlignmentY(1.0F);
        btn_nguoidung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nguoidung.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nguoidung.setIconTextGap(5);
        btn_nguoidung.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_nguoidung.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nguoidung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nguoidungActionPerformed(evt);
            }
        });

        btn_doimatkhau.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_doimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ changePassword48x48.png"))); // NOI18N
        btn_doimatkhau.setText("Đổi mật khẩu");
        btn_doimatkhau.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_doimatkhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_doimatkhau.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_doimatkhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_doimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doimatkhauActionPerformed(evt);
            }
        });

        btn_dangxuat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogOut48x48.png"))); // NOI18N
        btn_dangxuat.setText("Đăng xuất");
        btn_dangxuat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_dangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dangxuat.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_dangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btn_gioithieu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_gioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help48x48.png"))); // NOI18N
        btn_gioithieu.setText("Giới thiệu");
        btn_gioithieu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_gioithieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_gioithieu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_gioithieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_gioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gioithieuActionPerformed(evt);
            }
        });

        btn_gioithieu1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_gioithieu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help48x48.png"))); // NOI18N
        btn_gioithieu1.setText("Khuyến mãi");
        btn_gioithieu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_gioithieu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_gioithieu1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_gioithieu1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_gioithieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gioithieu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_htLayout = new javax.swing.GroupLayout(pnl_ht);
        pnl_ht.setLayout(pnl_htLayout);
        pnl_htLayout.setHorizontalGroup(
            pnl_htLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_htLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_nguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_doimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_gioithieu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_gioithieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_htLayout.setVerticalGroup(
            pnl_htLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_htLayout.createSequentialGroup()
                .addGroup(pnl_htLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_gioithieu1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_htLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_doimatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addComponent(btn_gioithieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_nguoidung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout pnl_hethongLayout = new javax.swing.GroupLayout(pnl_hethong);
        pnl_hethong.setLayout(pnl_hethongLayout);
        pnl_hethongLayout.setHorizontalGroup(
            pnl_hethongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_hethongLayout.createSequentialGroup()
                .addComponent(pnl_ht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 820, Short.MAX_VALUE))
        );
        pnl_hethongLayout.setVerticalGroup(
            pnl_hethongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_ht, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbn_menu.addTab("Hệ Thống", pnl_hethong);

        pnl_muonthongke.setBackground(new java.awt.Color(0, 153, 204));

        pnl_muontragiahan.setBackground(new java.awt.Color(0, 153, 204));
        pnl_muontragiahan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_muontratieude.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_muontratieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_muontratieude.setText("Mượn - trả - gia hạn sách-phạt");
        lbl_muontratieude.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_chomuon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_chomuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/theory48x48.png"))); // NOI18N
        btn_chomuon.setText("Cho Mượn");
        btn_chomuon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_chomuon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_chomuon.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_chomuon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_chomuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chomuonActionPerformed(evt);
            }
        });

        btn_trasachgiahan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_trasachgiahan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Things-Book48x48.png"))); // NOI18N
        btn_trasachgiahan.setText("Trả Sách - Gia Hạn");
        btn_trasachgiahan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_trasachgiahan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_trasachgiahan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_trasachgiahan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_trasachgiahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trasachgiahanActionPerformed(evt);
            }
        });

        btn_chomuon1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_chomuon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/theory48x48.png"))); // NOI18N
        btn_chomuon1.setText("Phạt");
        btn_chomuon1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_chomuon1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_chomuon1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_chomuon1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_chomuon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chomuon1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_muontragiahanLayout = new javax.swing.GroupLayout(pnl_muontragiahan);
        pnl_muontragiahan.setLayout(pnl_muontragiahanLayout);
        pnl_muontragiahanLayout.setHorizontalGroup(
            pnl_muontragiahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_muontragiahanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_chomuon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_trasachgiahan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_chomuon1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbl_muontratieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_muontragiahanLayout.setVerticalGroup(
            pnl_muontragiahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_muontragiahanLayout.createSequentialGroup()
                .addGroup(pnl_muontragiahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_trasachgiahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_chomuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_chomuon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_muontratieude, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_baocao.setBackground(new java.awt.Color(0, 153, 204));
        pnl_baocao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_baocaotieude.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_baocaotieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_baocaotieude.setText("Báo Cáo - Thống Kê");
        lbl_baocaotieude.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_sachcon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_sachcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/0012-Books-icon32x32.png"))); // NOI18N
        btn_sachcon.setText("Sách");
        btn_sachcon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_sachcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sachcon.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_sachcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_sachcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sachconActionPerformed(evt);
            }
        });

        btn_doanhthu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_doanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chart-icon32x32.png"))); // NOI18N
        btn_doanhthu.setText("Doanh thu");
        btn_doanhthu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_doanhthu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_doanhthu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_doanhthu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_doanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doanhthuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_baocaoLayout = new javax.swing.GroupLayout(pnl_baocao);
        pnl_baocao.setLayout(pnl_baocaoLayout);
        pnl_baocaoLayout.setHorizontalGroup(
            pnl_baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_baocaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_sachcon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_doanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbl_baocaotieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_baocaoLayout.setVerticalGroup(
            pnl_baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_baocaoLayout.createSequentialGroup()
                .addGroup(pnl_baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_sachcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_doanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_baocaotieude, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnl_muonthongkeLayout = new javax.swing.GroupLayout(pnl_muonthongke);
        pnl_muonthongke.setLayout(pnl_muonthongkeLayout);
        pnl_muonthongkeLayout.setHorizontalGroup(
            pnl_muonthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_muonthongkeLayout.createSequentialGroup()
                .addComponent(pnl_muontragiahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_baocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 776, Short.MAX_VALUE))
        );
        pnl_muonthongkeLayout.setVerticalGroup(
            pnl_muonthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_muontragiahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_baocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbn_menu.addTab("Mượn Sách - Trả Sách - Thống Kê", pnl_muonthongke);

        pnl_CapnhapQuanly.setBackground(new java.awt.Color(0, 153, 204));

        pnl_docgia.setBackground(new java.awt.Color(0, 153, 204));
        pnl_docgia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_docgiatieude.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_docgiatieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_docgiatieude.setText("Độc giả");
        lbl_docgiatieude.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_danhsachdocgia.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_danhsachdocgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-group48x48.png"))); // NOI18N
        btn_danhsachdocgia.setText("Danh sách");
        btn_danhsachdocgia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_danhsachdocgia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_danhsachdocgia.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_danhsachdocgia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_danhsachdocgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_danhsachdocgiaActionPerformed(evt);
            }
        });

        btn_nhapexdocgia.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_nhapexdocgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excel-icon24x24.png"))); // NOI18N
        btn_nhapexdocgia.setText("nhập từ Excel");
        btn_nhapexdocgia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_nhapexdocgia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout pnl_docgiaLayout = new javax.swing.GroupLayout(pnl_docgia);
        pnl_docgia.setLayout(pnl_docgiaLayout);
        pnl_docgiaLayout.setHorizontalGroup(
            pnl_docgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_docgiaLayout.createSequentialGroup()
                .addComponent(lbl_docgiatieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnl_docgiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_danhsachdocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_nhapexdocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_docgiaLayout.setVerticalGroup(
            pnl_docgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_docgiaLayout.createSequentialGroup()
                .addGroup(pnl_docgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_danhsachdocgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_docgiaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_nhapexdocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_docgiatieude, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_nhanvien.setBackground(new java.awt.Color(0, 153, 204));
        pnl_nhanvien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_nhanvientieude.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_nhanvientieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nhanvientieude.setText("Nhân viên thư viện");
        lbl_nhanvientieude.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_danhsachnhanvien.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_danhsachnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-group-icon48x48.png"))); // NOI18N
        btn_danhsachnhanvien.setText("Danh sách");
        btn_danhsachnhanvien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_danhsachnhanvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_danhsachnhanvien.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_danhsachnhanvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_danhsachnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_danhsachnhanvienActionPerformed(evt);
            }
        });

        btn_phanquyen.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_phanquyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-rating-icon.png"))); // NOI18N
        btn_phanquyen.setText("quyền");
        btn_phanquyen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_phanquyen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_phanquyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phanquyenActionPerformed(evt);
            }
        });

        btn_nhapexdocgia1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_nhapexdocgia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excel-icon24x24.png"))); // NOI18N
        btn_nhapexdocgia1.setText("nhập từ Excel");
        btn_nhapexdocgia1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_nhapexdocgia1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout pnl_nhanvienLayout = new javax.swing.GroupLayout(pnl_nhanvien);
        pnl_nhanvien.setLayout(pnl_nhanvienLayout);
        pnl_nhanvienLayout.setHorizontalGroup(
            pnl_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_nhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_danhsachnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_phanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nhapexdocgia1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbl_nhanvientieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_nhanvienLayout.setVerticalGroup(
            pnl_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_nhanvienLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnl_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_nhanvienLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_nhapexdocgia1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_phanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_danhsachnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nhanvientieude, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_sach.setBackground(new java.awt.Color(0, 153, 204));
        pnl_sach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sách");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButton19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/research48x48.png"))); // NOI18N
        jButton19.setText("Danh mục");
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button-Add-icon24x24.png"))); // NOI18N
        jButton20.setText("Thêm");
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Filesystem-file-broken32x32.png"))); // NOI18N
        jButton21.setText("Sách hỏng");
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_sachLayout = new javax.swing.GroupLayout(pnl_sach);
        pnl_sach.setLayout(pnl_sachLayout);
        pnl_sachLayout.setHorizontalGroup(
            pnl_sachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_sachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_sachLayout.setVerticalGroup(
            pnl_sachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_sachLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnl_sachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_sachLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_kho.setBackground(new java.awt.Color(0, 153, 204));
        pnl_kho.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Kho");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButton23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/payment-icon48x48.png"))); // NOI18N
        jButton23.setText("Thanh lý");
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/import-icon48x48.png"))); // NOI18N
        jButton24.setText("Nhập kho");
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton24.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_khoLayout = new javax.swing.GroupLayout(pnl_kho);
        pnl_kho.setLayout(pnl_khoLayout);
        pnl_khoLayout.setHorizontalGroup(
            pnl_khoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_khoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_khoLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        pnl_khoLayout.setVerticalGroup(
            pnl_khoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_khoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnl_khoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_tacgiatheloai.setBackground(new java.awt.Color(0, 153, 204));
        pnl_tacgiatheloai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tác giả - Thể loại - Nhà cung cấp");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButton25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/authors-icon48x48.png"))); // NOI18N
        jButton25.setText("Tác giả");
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton25.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton25.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Categories-gnome-applications-icon48x48.png"))); // NOI18N
        jButton26.setText("Thể loại");
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton26.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton26.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/authors-icon48x48.png"))); // NOI18N
        jButton27.setText("Nhà CC");
        jButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton27.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton27.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_tacgiatheloaiLayout = new javax.swing.GroupLayout(pnl_tacgiatheloai);
        pnl_tacgiatheloai.setLayout(pnl_tacgiatheloaiLayout);
        pnl_tacgiatheloaiLayout.setHorizontalGroup(
            pnl_tacgiatheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tacgiatheloaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_tacgiatheloaiLayout.setVerticalGroup(
            pnl_tacgiatheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tacgiatheloaiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnl_tacgiatheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_tacgiatheloaiLayout.createSequentialGroup()
                        .addGroup(pnl_tacgiatheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton25)
                            .addComponent(jButton27))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnl_CapnhapQuanlyLayout = new javax.swing.GroupLayout(pnl_CapnhapQuanly);
        pnl_CapnhapQuanly.setLayout(pnl_CapnhapQuanlyLayout);
        pnl_CapnhapQuanlyLayout.setHorizontalGroup(
            pnl_CapnhapQuanlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CapnhapQuanlyLayout.createSequentialGroup()
                .addComponent(pnl_docgia, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_sach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_kho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_tacgiatheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_CapnhapQuanlyLayout.setVerticalGroup(
            pnl_CapnhapQuanlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_docgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_nhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_sach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_kho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_tacgiatheloai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbn_menu.addTab("Cập nhập - Quản lý", pnl_CapnhapQuanly);

        pnl_Congcu.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout pnl_CongcuLayout = new javax.swing.GroupLayout(pnl_Congcu);
        pnl_Congcu.setLayout(pnl_CongcuLayout);
        pnl_CongcuLayout.setHorizontalGroup(
            pnl_CongcuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1361, Short.MAX_VALUE)
        );
        pnl_CongcuLayout.setVerticalGroup(
            pnl_CongcuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        tbn_menu.addTab("Công Cụ", pnl_Congcu);

        pnl_thongtin.setBackground(new java.awt.Color(51, 153, 255));
        pnl_thongtin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_maytru.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_maytru.setText("Máy chủ :");

        lbl_nguoisudung.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_nguoisudung.setText("Người sử dụng :");

        lbl_quyenhan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_quyenhan.setText("Quyền hạn :");

        javax.swing.GroupLayout pnl_thongtinLayout = new javax.swing.GroupLayout(pnl_thongtin);
        pnl_thongtin.setLayout(pnl_thongtinLayout);
        pnl_thongtinLayout.setHorizontalGroup(
            pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_thongtinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_maytru)
                .addGap(385, 385, 385)
                .addComponent(lbl_nguoisudung)
                .addGap(212, 212, 212)
                .addComponent(lbl_quyenhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_thongtinLayout.setVerticalGroup(
            pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_thongtinLayout.createSequentialGroup()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbl_quyenhan))
            .addGroup(pnl_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_maytru)
                .addComponent(lbl_nguoisudung))
        );

        tbn_main.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbn_menu)
            .addComponent(tbn_main)
            .addComponent(pnl_thongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(tbn_main)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_thongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1386, 749));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_doanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doanhthuActionPerformed
        pnl_doanhthu pnl = new pnl_doanhthu();
        BLL_main.themtab("Doanh thu", tbn_main, pnl);
    }//GEN-LAST:event_btn_doanhthuActionPerformed

    private void btn_nguoidungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nguoidungActionPerformed
        pnl_nguoidung pnl = new pnl_nguoidung();
        BLL_main.themtab("Người dùng", tbn_main, pnl);
    }//GEN-LAST:event_btn_nguoidungActionPerformed

    private void btn_doimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doimatkhauActionPerformed
        frm_doimatkhau pnl = new frm_doimatkhau();
        pnl.show();
    }//GEN-LAST:event_btn_doimatkhauActionPerformed

    private void btn_gioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gioithieuActionPerformed
        pnl_gioithieu pnl = new pnl_gioithieu();
        BLL_main.themtab("Giới thiệu", tbn_main, pnl);
        
    }//GEN-LAST:event_btn_gioithieuActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        pnl_danhmucsach pnl = new pnl_danhmucsach();
        BLL_main.themtab("Danh mục sách", tbn_main, pnl);
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        frm_thongtinsach frm = new frm_thongtinsach();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void btn_phanquyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phanquyenActionPerformed
        pnl_Quyen pnl = new pnl_Quyen();
        BLL_main.themtab("Quyền", tbn_main, pnl);
        BLL.BLL_Quyen.DLTable(tblQuyen,DAL_Quyen.GetAll());
    }//GEN-LAST:event_btn_phanquyenActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        pnl_TheLoai pnl = new pnl_TheLoai();
        BLL_main.themtab("Thể Loại", tbn_main, pnl);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void btn_chomuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chomuonActionPerformed
        pnl_PhieuThue pnl = new pnl_PhieuThue();
        BLL_main.themtab("Phiếu mượn", tbn_main, pnl);
    }//GEN-LAST:event_btn_chomuonActionPerformed

    private void btn_danhsachdocgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_danhsachdocgiaActionPerformed
        pnl_DocGia pnl = new pnl_DocGia();
        BLL_main.themtab("Độc giả", tbn_main, pnl);
    }//GEN-LAST:event_btn_danhsachdocgiaActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        pnl_TacGia pnl = new pnl_TacGia();
        BLL_main.themtab("Tác Giả", tbn_main, pnl);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void btn_chomuon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chomuon1ActionPerformed
        pnl_PhieuPhat pnl = new pnl_PhieuPhat();
        BLL_main.themtab("Phiếu Phạt", tbn_main, pnl);
    }//GEN-LAST:event_btn_chomuon1ActionPerformed

    private void btn_danhsachnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_danhsachnhanvienActionPerformed
        pnl_nhanvien pnl = new pnl_nhanvien();
        BLL_main.themtab("Nhân Viên", tbn_main, pnl);
    }//GEN-LAST:event_btn_danhsachnhanvienActionPerformed

    private void btn_trasachgiahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trasachgiahanActionPerformed
        pnl_giahan_trasach pnl = new pnl_giahan_trasach();
        BLL_main.themtab("Gia hạn-Trả sách", tbn_main, pnl);
    }//GEN-LAST:event_btn_trasachgiahanActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        pnl_nhacungcap pnl = new pnl_nhacungcap();
        BLL_main.themtab("NNhà cung cấp", tbn_main, pnl);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        pnl_Sachhong pnl = new pnl_Sachhong();
        BLL_main.themtab("Sách hỏng", tbn_main, pnl);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void btn_gioithieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gioithieu1ActionPerformed
        pnl_khuyenmai pnl = new pnl_khuyenmai();
        BLL_main.themtab("Khuyến mãi", tbn_main, pnl);
    }//GEN-LAST:event_btn_gioithieu1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        pnl_PhieuThanhLy pnl = new pnl_PhieuThanhLy();
        BLL_main.themtab("Thanh lý", tbn_main, pnl);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
       pnl_nhapkho pnl = new pnl_nhapkho();
        BLL_main.themtab("Nhập kho", tbn_main, pnl);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void btn_sachconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sachconActionPerformed
        pnl_baocao_sach pnl = new pnl_baocao_sach();
        BLL_main.themtab("Báo cáo", tbn_main, pnl);
    }//GEN-LAST:event_btn_sachconActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chomuon;
    private javax.swing.JButton btn_chomuon1;
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JButton btn_danhsachdocgia;
    private javax.swing.JButton btn_danhsachnhanvien;
    private javax.swing.JButton btn_doanhthu;
    private javax.swing.JButton btn_doimatkhau;
    private javax.swing.JButton btn_gioithieu;
    private javax.swing.JButton btn_gioithieu1;
    private javax.swing.JButton btn_nguoidung;
    private javax.swing.JButton btn_nhapexdocgia;
    private javax.swing.JButton btn_nhapexdocgia1;
    private javax.swing.JButton btn_phanquyen;
    private javax.swing.JButton btn_sachcon;
    private javax.swing.JButton btn_trasachgiahan;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_baocaotieude;
    private javax.swing.JLabel lbl_docgiatieude;
    private javax.swing.JLabel lbl_maytru;
    private javax.swing.JLabel lbl_muontratieude;
    private javax.swing.JLabel lbl_nguoisudung;
    private javax.swing.JLabel lbl_nhanvientieude;
    private javax.swing.JLabel lbl_quyenhan;
    private javax.swing.JPanel pnl_CapnhapQuanly;
    private javax.swing.JPanel pnl_Congcu;
    private javax.swing.JPanel pnl_baocao;
    private javax.swing.JPanel pnl_docgia;
    private javax.swing.JPanel pnl_hethong;
    private javax.swing.JPanel pnl_ht;
    private javax.swing.JPanel pnl_kho;
    private javax.swing.JPanel pnl_muonthongke;
    private javax.swing.JPanel pnl_muontragiahan;
    private javax.swing.JPanel pnl_nhanvien;
    private javax.swing.JPanel pnl_sach;
    private javax.swing.JPanel pnl_tacgiatheloai;
    private javax.swing.JPanel pnl_thongtin;
    private javax.swing.JTabbedPane tbn_main;
    private javax.swing.JTabbedPane tbn_menu;
    // End of variables declaration//GEN-END:variables
}
