/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_KhuyenMai;
import BLL.ChuyenDoi_ThongBao;
import DAL.DAL_Sach;
import GUI.khuyenmai.pnl_KoMaSach;
import GUI.khuyenmai.pnl_MaSach;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huy Nhan
 */
public class pnl_khuyenmai extends javax.swing.JPanel {

    /**
     * Creates new form pnl_khuyenmai
     */
    public pnl_khuyenmai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btn_xoa = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_km = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        rbt_tienHD = new javax.swing.JRadioButton();
        rbt_soluong = new javax.swing.JRadioButton();
        rbt_donggia = new javax.swing.JRadioButton();
        rbt_voucher = new javax.swing.JRadioButton();
        rbt_tungcuon = new javax.swing.JRadioButton();

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_xoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_them.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbl_km.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_km);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các Loại Khuyến Mãi", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        rbt_tienHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbt_tienHD.setText("KM Theo Số Tiền Hóa Đơn");
        rbt_tienHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_tienHDActionPerformed(evt);
            }
        });

        rbt_soluong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbt_soluong.setText("KM Theo Số Lượng Sách");
        rbt_soluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_soluongActionPerformed(evt);
            }
        });

        rbt_donggia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbt_donggia.setText("KM Đồng Giá");
        rbt_donggia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_donggiaActionPerformed(evt);
            }
        });

        rbt_voucher.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbt_voucher.setText("KM Coupon, Voucher");
        rbt_voucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_voucherActionPerformed(evt);
            }
        });

        rbt_tungcuon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbt_tungcuon.setText("KM Giảm Giá Theo Từng Cuốn");
        rbt_tungcuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_tungcuonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbt_tienHD)
                    .addComponent(rbt_soluong)
                    .addComponent(rbt_donggia)
                    .addComponent(rbt_voucher)
                    .addComponent(rbt_tungcuon))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(rbt_tienHD)
                .addGap(18, 18, 18)
                .addComponent(rbt_soluong)
                .addGap(18, 18, 18)
                .addComponent(rbt_donggia)
                .addGap(18, 18, 18)
                .addComponent(rbt_voucher)
                .addGap(18, 18, 18)
                .addComponent(rbt_tungcuon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public static int Them = 0;
    private void rbt_tienHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_tienHDActionPerformed
        rbt_donggia.setSelected(false);
        rbt_soluong.setSelected(false);
        rbt_tienHD.setSelected(true);
        rbt_tungcuon.setSelected(false);
        rbt_voucher.setSelected(false);
        BLL.BLL_KhuyenMai.SettableKMTienHD(tbl_km,DAL.DAL_KhuyenMai.GetKMTienHD());
        Them = 1;
    }//GEN-LAST:event_rbt_tienHDActionPerformed

    private void rbt_soluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_soluongActionPerformed
        rbt_donggia.setSelected(false);
        rbt_soluong.setSelected(true);
        rbt_tienHD.setSelected(false);
        rbt_tungcuon.setSelected(false);
        rbt_voucher.setSelected(false);
        BLL.BLL_KhuyenMai.SettableKMSLSach(tbl_km, DAL.DAL_KhuyenMai.GetKMSLSach());
        Them = 2;
    }//GEN-LAST:event_rbt_soluongActionPerformed

    private void rbt_donggiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_donggiaActionPerformed
        rbt_donggia.setSelected(true);
        rbt_soluong.setSelected(false);
        rbt_tienHD.setSelected(false);
        rbt_tungcuon.setSelected(false);
        rbt_voucher.setSelected(false);
        BLL.BLL_KhuyenMai.SettableKMDongGia(tbl_km, DAL.DAL_KhuyenMai.GetKMDongGia());
        Them = 3;
    }//GEN-LAST:event_rbt_donggiaActionPerformed

    private void rbt_voucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_voucherActionPerformed
        rbt_donggia.setSelected(false);
        rbt_soluong.setSelected(false);
        rbt_tienHD.setSelected(false);
        rbt_tungcuon.setSelected(false);
        rbt_voucher.setSelected(true);
        BLL.BLL_KhuyenMai.SettableKMVoucher(tbl_km, DAL.DAL_KhuyenMai.GetKMVoucher());
        Them = 4;
    }//GEN-LAST:event_rbt_voucherActionPerformed

    private void rbt_tungcuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_tungcuonActionPerformed
        rbt_donggia.setSelected(false);
        rbt_soluong.setSelected(false);
        rbt_tienHD.setSelected(false);
        rbt_tungcuon.setSelected(true);
        rbt_voucher.setSelected(false);
        BLL.BLL_KhuyenMai.SettableKMCuon(tbl_km, DAL.DAL_KhuyenMai.GetKMCuon());
        Them = 5;
    }//GEN-LAST:event_rbt_tungcuonActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        switch (Them) {
            case 1:
                GUI.khuyenmai.pnl_KoMaSach pnl1 = new pnl_KoMaSach();
                pnl1.show();
                GUI.khuyenmai.pnl_KoMaSach.lbl_GiaSach.setText("Giảm Giá");
                GUI.khuyenmai.pnl_KoMaSach.lbl_TT.setText("Số Tiền HD");
            //---------------------------------------------------------------
            //show hộp thoại xác nhận
            int luachon1 = JOptionPane.showConfirmDialog(new JFrame(), pnl1, "Nhập Thông Tin", JOptionPane.YES_NO_OPTION);
            
            // kiểm tra xem người dùng bấm vào yes hay no
            if (luachon1 == JOptionPane.YES_OPTION) {
                String ngaybatdau, ngayketthuc,tenKM,gia;
                ngaybatdau = GUI.khuyenmai.pnl_KoMaSach.txt_NgayBatDau.getText();
                ngayketthuc = GUI.khuyenmai.pnl_KoMaSach.txt_NgayKetThuc.getText();
                tenKM = GUI.khuyenmai.pnl_KoMaSach.txt_KM.getText();
                gia = GUI.khuyenmai.pnl_KoMaSach.txt_giasach.getText();
            try {
                BLL_KhuyenMai.insertKMKMTienHD(ngaybatdau, ngayketthuc, gia, tenKM, GUI.khuyenmai.pnl_KoMaSach.txt_TT.getText());
            } catch (ParseException ex) {
                Logger.getLogger(pnl_khuyenmai.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                }
                break;
            case 2:
                    GUI.khuyenmai.pnl_KoMaSach pnl2 = new pnl_KoMaSach();
                pnl2.show();
                GUI.khuyenmai.pnl_KoMaSach.lbl_GiaSach.setText("Giảm Giá");
                GUI.khuyenmai.pnl_KoMaSach.lbl_TT.setText("Số Lượng Sách");
            //---------------------------------------------------------------
            //show hộp thoại xác nhận
            int luachon2 = JOptionPane.showConfirmDialog(new JFrame(), pnl2, "Nhập Thông Tin", JOptionPane.YES_NO_OPTION);
            
            // kiểm tra xem người dùng bấm vào yes hay no
            if (luachon2 == JOptionPane.YES_OPTION) {
                String ngaybatdau, ngayketthuc,tenKM,gia;
                ngaybatdau = GUI.khuyenmai.pnl_KoMaSach.txt_NgayBatDau.getText();
                ngayketthuc = GUI.khuyenmai.pnl_KoMaSach.txt_NgayKetThuc.getText();
                tenKM = GUI.khuyenmai.pnl_KoMaSach.txt_KM.getText();
                gia = GUI.khuyenmai.pnl_KoMaSach.txt_giasach.getText();
            try {
                BLL_KhuyenMai.insertKMKMSLSach(ngaybatdau, ngayketthuc, gia, tenKM, GUI.khuyenmai.pnl_KoMaSach.txt_TT.getText());
            } catch (ParseException ex) {
                Logger.getLogger(pnl_khuyenmai.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                }
                break;
            case 3:
                GUI.khuyenmai.pnl_MaSach pnl = new pnl_MaSach();
                pnl.show();
                GUI.khuyenmai.pnl_MaSach.lbl_GiaSach.setText("Đồng Giá");
                BLL_KhuyenMai.ThongTinSach((DefaultTableModel) GUI.khuyenmai.pnl_MaSach.tblSach.getModel()//
                    , DAL_Sach.GetAll());
            //---------------------------------------------------------------
            //show hộp thoại xác nhận
            int luachon = JOptionPane.showConfirmDialog(new JFrame(), pnl, "Nhập Thông Tin", JOptionPane.YES_NO_OPTION);
            
            // kiểm tra xem người dùng bấm vào yes hay no
            if (luachon == JOptionPane.YES_OPTION) {
                String ngaybatdau, ngayketthuc,tenKM,gia;
                ngaybatdau = GUI.khuyenmai.pnl_MaSach.txt_NgayBatDau.getText();
                ngayketthuc = GUI.khuyenmai.pnl_MaSach.txt_NgayKetThuc.getText();
                tenKM = GUI.khuyenmai.pnl_MaSach.txt_KM.getText();
                gia = GUI.khuyenmai.pnl_MaSach.txt_giasach.getText();
                for (int i = 0; i < GUI.khuyenmai.pnl_MaSach.tbl_sachkm.getRowCount(); i++) {
                    try {
                        BLL_KhuyenMai.insertKMDongGia(ngaybatdau, ngayketthuc, gia, tenKM, Integer.parseInt(GUI.khuyenmai.pnl_MaSach.tbl_sachkm.getValueAt(i, 0).toString()));
                    } catch (ParseException ex) {
                        Logger.getLogger(pnl_khuyenmai.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                }
                
                break;
            case 4:
                    GUI.khuyenmai.pnl_KoMaSach pnl4 = new pnl_KoMaSach();
                pnl4.show();
                GUI.khuyenmai.pnl_KoMaSach.lbl_GiaSach.setText("Giảm Giá");
                GUI.khuyenmai.pnl_KoMaSach.lbl_TT.setText("Coupon, Voucher");
            //---------------------------------------------------------------
            //show hộp thoại xác nhận
            int luachon4 = JOptionPane.showConfirmDialog(new JFrame(), pnl4, "Nhập Thông Tin", JOptionPane.YES_NO_OPTION);
            
            // kiểm tra xem người dùng bấm vào yes hay no
            if (luachon4 == JOptionPane.YES_OPTION) {
                String ngaybatdau, ngayketthuc,tenKM,gia;
                ngaybatdau = GUI.khuyenmai.pnl_KoMaSach.txt_NgayBatDau.getText();
                ngayketthuc = GUI.khuyenmai.pnl_KoMaSach.txt_NgayKetThuc.getText();
                tenKM = GUI.khuyenmai.pnl_KoMaSach.txt_KM.getText();
                gia = GUI.khuyenmai.pnl_KoMaSach.txt_giasach.getText();
            try {
                BLL_KhuyenMai.insertKMVoucher(ngaybatdau, ngayketthuc, gia, tenKM, GUI.khuyenmai.pnl_KoMaSach.txt_TT.getText());
            } catch (ParseException ex) {
                Logger.getLogger(pnl_khuyenmai.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                }
                break;
            case 5:
                GUI.khuyenmai.pnl_MaSach pnlCuon = new pnl_MaSach();
                pnlCuon.show();
                GUI.khuyenmai.pnl_MaSach.lbl_GiaSach.setText("Giảm Giá %");
                BLL_KhuyenMai.ThongTinSach((DefaultTableModel) GUI.khuyenmai.pnl_MaSach.tblSach.getModel()//
                    , DAL_Sach.GetAll());
            //---------------------------------------------------------------
            //show hộp thoại xác nhận
            int luachon5 = JOptionPane.showConfirmDialog(new JFrame(), pnlCuon, "Nhập Thông Tin", JOptionPane.YES_NO_OPTION);
            
            // kiểm tra xem người dùng bấm vào yes hay no
            if (luachon5 == JOptionPane.YES_OPTION) {
                String ngaybatdau, ngayketthuc,tenKM,gia;
                ngaybatdau = GUI.khuyenmai.pnl_MaSach.txt_NgayBatDau.getText();
                ngayketthuc = GUI.khuyenmai.pnl_MaSach.txt_NgayKetThuc.getText();
                tenKM = GUI.khuyenmai.pnl_MaSach.txt_KM.getText();
                gia = GUI.khuyenmai.pnl_MaSach.txt_giasach.getText();
                for (int i = 0; i < GUI.khuyenmai.pnl_MaSach.tbl_sachkm.getRowCount(); i++) {
                    try {
                        BLL_KhuyenMai.insertKMCuon(ngaybatdau, ngayketthuc, gia, tenKM, Integer.parseInt(GUI.khuyenmai.pnl_MaSach.tbl_sachkm.getValueAt(i, 0).toString()));
                    } catch (ParseException ex) {
                        Logger.getLogger(pnl_khuyenmai.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                }
                break;
            default:
                ChuyenDoi_ThongBao.ThongBao_Loi("Bạn chưa chọn chức năng để thêm khuyến mãi", "Lỗi thêm Khuyến Mãi");
                break;
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        //kiểm tra người dùng click mấy lần
        
        int row = tbl_km.getSelectedRow();
        
        switch (Them) {
            case 1:
                DAL.DAL_KhuyenMai.Xoa_KhuyenMai(tbl_km.getValueAt(row, 1).toString());
                BLL.BLL_KhuyenMai.SettableKMTienHD(tbl_km,DAL.DAL_KhuyenMai.GetKMTienHD());
                break;
            case 2:
                DAL.DAL_KhuyenMai.Xoa_KhuyenMai(tbl_km.getValueAt(row, 1).toString());
                BLL.BLL_KhuyenMai.SettableKMSLSach(tbl_km, DAL.DAL_KhuyenMai.GetKMSLSach());
                break;
            case 3:
                DAL.DAL_KhuyenMai.Xoa_KhuyenMai(tbl_km.getValueAt(row, 1).toString());
                BLL.BLL_KhuyenMai.SettableKMDongGia(tbl_km, DAL.DAL_KhuyenMai.GetKMDongGia());
                break;
            case 4:
                DAL.DAL_KhuyenMai.Xoa_KhuyenMai(tbl_km.getValueAt(row, 1).toString());
                BLL.BLL_KhuyenMai.SettableKMVoucher(tbl_km, DAL.DAL_KhuyenMai.GetKMVoucher());
                break;
            case 5:
                DAL.DAL_KhuyenMai.Xoa_KhuyenMai(tbl_km.getValueAt(row, 1).toString());
                BLL.BLL_KhuyenMai.SettableKMCuon(tbl_km, DAL.DAL_KhuyenMai.GetKMCuon());
                break;
            default:
                ChuyenDoi_ThongBao.ThongBao_Loi("Bạn chưa chọn chức năng để Xóa khuyến mãi", "Lỗi thêm Khuyến Mãi");
                break;
        }
    }//GEN-LAST:event_btn_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JRadioButton rbt_donggia;
    public static javax.swing.JRadioButton rbt_soluong;
    public static javax.swing.JRadioButton rbt_tienHD;
    public static javax.swing.JRadioButton rbt_tungcuon;
    public static javax.swing.JRadioButton rbt_voucher;
    public static javax.swing.JTable tbl_km;
    // End of variables declaration//GEN-END:variables
}
